/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bank_copy: typeof import('./src/components/bank_copy/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconCommunity: (typeof import('./src/components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./src/components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./src/components/icons/IconTooling.vue'))['default']
    Iphone13: typeof import('./src/components/middle/iphone13/iphone13.vue')['default']
    'Iphone13以上': typeof import('./src/components/middle/iphone13以上/iphone13以上.vue')['default']
    Iphone7: typeof import('./src/components/middle/iphone7/iphone7.vue')['default']
    'IphoneX以上': typeof import('./src/components/middle/iphoneX以上/iphoneX以上.vue')['default']
    Left: typeof import('./src/components/left/index.vue')['default']
    Main_home: typeof import('./src/components/main_home/index.vue')['default']
    Main_nav: typeof import('./src/components/main_nav/index.vue')['default']
    Middle: typeof import('./src/components/bank_copy/c-cpns/middle/index.vue')['default']
    Right: typeof import('./src/components/right/right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Type: typeof import('./src/components/middle/iphoneX以上/type/index.vue')['default']
  }
}
